name: 'SCP Uploader'
description: 'Deploy/upload files via SSH using key based authentication'
author: 'Moonpath'
inputs:
  host:
    description: 'remote host'
    required: true
  username:
    description: 'remote user'
    required: true
  port:
    description: 'remote port'
    default: 22
  key:
    description: 'ssh private key (~/.ssh/id_rsa)'
    required: true
  source:
    description: 'source files path'
    required: false
  target:
    description: 'destination path'
    required: false
  before:
    description: 'command to execute before transfer'
    required: false
  after:
    description: 'command to execute after transfer'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'external-link'
  color: 'red'
